# Generated by Django 4.2.6 on 2023-11-28 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=650)),
                ('description', models.CharField(max_length=700)),
                ('url', models.CharField(max_length=500)),
                ('day', models.CharField(max_length=11)),
                ('published_at', models.DateTimeField(default=datetime.datetime(2023, 11, 28, 17, 8, 54, 558263, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
