# Generated by Django 4.2.7 on 2023-11-28 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlash_news_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 18, 22, 21, 292667, tzinfo=datetime.timezone.utc)),
        ),
    ]
