# Generated by Django 4.2.7 on 2023-11-28 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlash_news_api', '0003_newsarticle_alter_newsmodel_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 21, 16, 14, 401093, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
