# Generated by Django 4.2.7 on 2023-11-28 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlash_news_api', '0004_delete_newsarticle_alter_newsmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 21, 17, 2, 104448, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
